### ISSUE TITLE
Weapon swap error

### ISSUE THREAD

**Issue by PaolottoGames** [The-DoomMan/ULTRASKINS#5]
the weapon texture only remains if you keep that weapon, changing variation or weapon itself will set the texture into the defult ones

**Comment by The-DoomMan** [comment]
iam not sure if this is in the current public version of ultraskins, but there should be a "RELOAD SKINS" button in teh weapons page in the shop terminal, if not, press k on your keyboard to reload all textures

**Comment by PaolottoGames** [comment]
it does relode textures when you Press it, but you cant do it every time when you swap a weapon
