### ISSUE TITLE
Enemy projectile texture doesnt work

### ISSUE THREAD

**Issue by PaolottoGames** [The-DoomMan/ULTRASKINS#7]
the name speaks itself, it does not work

**Comment by The-DoomMan** [comment]
this mod isnt supposed to change enemy projectile textures, the skull texture is part of the core eject model it self, or was part of it.

**Comment by PaolottoGames** [comment]
> this mod isnt supposed to change enemy projectile textures, the skull texture is part of the core eject model it self, or was part of it.

Ohhhhh, makes sense
